package swimmingContest.network;

public enum RequestType {
    LOGIN, LOGOUT,GET_PARTICIPANTS_SWIMMINGEVENT,GET_SWIMMINGEVENTS_PARTICIPANT,ADD_SIGNUP,
    FIND_USER_NAME_PASS,FIND_USER_NAME,
    FIND_ALL_PARTICIPANTS,FIND_PARTICIPANT,ADD_PARTICIPANT,
    GET_NUMBER_PARTICIPANTS_BY_SWIMMINGEVENT,
    FIND_ALL_SWIMMINGEVENT,FIND_SWIMMMINGEVENT,
    FIND_ALL_SIGNUPS;
}

