package swimmingContest.network;

public enum ResponseType {
    OK,ERROR,GET_PARTICIPANTS_SWIMMINGEVENT,GET_SWIMMINGEVENTS_PARTICIPANT,ADD_SIGNUP,ADDED_SIGNUP,FIND_USER_NAME_PASS,FIND_USER_NAME,
    FIND_ALL_PARTICIPANTS,FIND_PARTICIPANT,ADD_PARTICIPANT,
    GET_NUMBER_PARTICIPANTS_BY_SWIMMINGEVENT,
    FIND_ALL_SWIMMINGEVENT,FIND_SWIMMMINGEVENT,
    FIND_ALL_SIGNUPS;
}
